[general]
import = [
    "~/.config/alacritty/themes/themes/iris.toml"
]

[colors.primary]
background = "#110f1c"

[font]
size = 8.0

[font.normal]
family = "comicmono"

[window]
opacity = 0.75
padding.x = 10
padding.y = 10

